const work = [
    {
      "title": "お菓子屋の仮想サイト",
      "overview": "お菓子屋の仮想サイトです。",
      "feature-1": "サイト訪問者に印象の残るサイトを目指し、ファーストビューのアニメーションに力を入れました。",
      "feature-2": "また、こだわりセクションでは、スクロールをトリガーにして時間差でアニメーションをスタートさせるために、GSAPを取り入れました。",
      "lang": "HTML5/CSS3、jQuery、GSAP",
      "period": "3日",
      "souce-code": "https://github.com/kuma9732/sweets-site",
      "show-text":"Show Page",
      "show-page":"https://kuma9732.github.io/sweets-site",
      "comment":"",
    },
    {
      "title": "電子部品会社の仮想サイト",
      "overview": "電子部品会社の仮想サイトです。",
      "feature-1": "作業簡略化を目的に、文章をmaster.jsに一括管理し、サイトへの反映は、URLの数字を割り振ることで、それぞれの製品名、サイズ等を表示させました。",
      "feature-2": "これにより、製品情報の追加・変更の場合も作業を簡略化することが可能となります。",
      "lang": "HTML5/CSS3、jQuery",
      "period": "7日",
      "souce-code": "https://github.com/kuma9732/manufacturer-company-site",
      "show-text":"Show Page",
      "show-page":"https://kuma9732.github.io/manufacturer-company-site",
      "comment":"",
    },
    {
      "title": "電子部品会社の商品登録ページ",
      "overview": "商品掲載者が自社の商品をfirebaseのDatabase上にアップするためのサイトです。",
      "feature-1": "商品dataをfirebaseのDatabaseに登録することができます。",
      "feature-2": "登録したdataを削除・修正することができます。",
      "lang": "HTML5/CSS3、jQuery、firebase",
      "period": "2日",
      "souce-code": "https://github.com/kuma9732/products-registration",
      "show-text":"注釈",
      "comment":"※このサイトは商品注文ページと注文内容確認ページと合わせて使います。",
    },
    {
      "title": "電子部品会社の商品注文ページ",
      "overview": "サイト訪問者は掲載されている商品を選択し、商品掲載者に商品を注文するためのサイトです。",
      "feature-1": "選択した商品をカートに登録し、カート内で内容(合計金額等)の確認や削除を行うことが出来ます。",
      "feature-2": "カート内の内容をfirebaseのDatabaseに登録することが出来ます。",
      "lang": "HTML5/CSS3、jQuery、firebase",
      "period": "2日",
      "souce-code": "https://github.com/kuma9732/products-order",
      "show-text":"注釈",
      "comment":"※このサイトは商品注文ページと注文内容確認ページと合わせて使います。",
    },
    {
      "title": "電子部品会社の注文内容確認ページ",
      "overview": "商品掲載者はサイト訪問者からの商品注文内容を確認するためのサイトです。",
      "feature-1": "firebaseのDatabaseに登録された注文内容データを家訓することが出来ます",
      "feature-2": "",
      "lang": "HTML5/CSS3、jQuery、firebase",
      "period": "1日",
      "souce-code": "https://github.com/kuma9732/manufacturer-company-site",
      "show-text":"注釈",
      "comment":"※このサイトは商品登録ページと商品注文ページと合わせて使います。",
    },
    {
      "title": "クリニックの仮想サイト",
      "overview": "クリニックの仮想サイトです。",
      "feature-1": "サイト訪問者が診察時間と場所が分かりやすいように、googleカレンダーとgoogleマップを追加しています。",
      "feature-2": "スマホ版では電話とWEB予約がしやすくするために、ファーストビューに専用のボタンを設置しています。",
      "lang": "HTML5/CSS3、jQuery",
      "period": "2日",
      "souce-code": "https://github.com/kuma9732/clinic-site",
      "show-text":"Show Page",
      "show-page":"https://kuma9732.github.io/clinic-site",
      "comment":"",
    },
    {
      "title": "建築会社の仮想サイト",
      "overview": "建築会社の仮想サイトです。",
      "feature-1": "全体的にシンプルなデザインにして、サイト訪問者が見やすいように作成しました。",
      "feature-2": "",
      "lang": "HTML5/CSS3、jQuery",
      "period": "2日",
      "souce-code": "https://github.com/kuma9732/construction-company-site",
      "show-text":"Show Page",
      "show-page":"https://kuma9732.github.io/manufacturer-company-site",
      "comment":"",
    },
    {
      "title": "ポートフォリオサイトサイト",
      "overview": "現在表示しているポートフォリオサイトサイトです。",
      "feature-1": "全体的にシンプルなデザインにして、サイト訪問者が見やすいように作成しました。",
      "lang": "HTML5/CSS3、jQuery、Bootstrap",
      "period": "1日",
      "souce-code": "https://github.com/kuma9732/Portfolio-site",
      "show-text":"Show Page",
      "show-page":"https://github.com/kuma9732/Portfolio-site",
      "comment":"",
    },
  ]